version: "3"
services:
    app:
        build:
            args:
                user: ${DOCKER_USER}
                group: ${DOCKER_GROUP}
                uid: ${DOCKER_UID}
            context: ./
            dockerfile: docker/Dockerfile
        image: laravel_library
        container_name: library_app
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/lib.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - libNet

    nginx:
        image: nginx:alpine
        container_name: lib_nginx
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - libNet

    # mariadb:
    #     image: mariadb:10.5
    #     container_name: lib_db
    #     restart: unless-stopped
    #     ports:
    #         - 3306:3306
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_ROOT_HOST: '%'
    #         MYSQL_USER: ${DB_USERNAME}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #     volumes:
    #         - libData:/var/lib/mysql/
    #         - ./docker/mariadb/lib.cnf:/etc/mysql/my.cnf
    #     networks:
    #         - libNet
    #     depends_on:
    #         - nginx

networks:
    libNet:
        driver: bridge

volumes:
    libData:
        driver: local
